django/shopping_mall/shopping_mall/urls.py
from django.contrib import admin
from django.urls import path
from user.views import index, RegisterView, LoginView, logout
from product.views import ProductList, ProductCreate, ProductDetail, ProductListAPI, ProductDetailAPI
from order.views import OrderCreate, OrderList

# 클래스의 경우에는 as_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('product/', ProductList.as_view()),
    path('product/create/', ProductCreate.as_view()),
    path('product/<int:pk>/', ProductDetail.as_view()),
    path('order/create/', OrderCreate.as_view()),
    path('order/', OrderList.as_view()),
    path('logout/', logout),
    path('api/product', ProductListAPI.as_view()),
    path('api/product/<int:pk>', ProductDetailAPI.as_view())

]

django/shopping_mall/product/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=256, verbose_name="PRODUCT NAME")
    price = models.IntegerField(verbose_name="PRODUCT PRICE")
    description = models.TextField(verbose_name="PRODUCT DESCRIPTION")
    stock = models.IntegerField(verbose_name="STOCK")
    register_date = models.DateTimeField(
        auto_now_add=True, verbose_name="REGI DATE")

    def __str__(self):
        return self.name

    class Meta:
        db_table = "Shopping_Product"
        verbose_name = "Product"
        verbose_name_plural = "Product"

django/shopping_mall/product/forms.py
from django import forms
from .models import Product



class RegisterForm(forms.Form):

    name = forms.CharField(error_messages={
        'required': "Please Enter the Name of the Product"
    }, max_length=64, label="NAME")
    price = forms.IntegerField(error_messages={
        'required': "Please Enter the Price"
    }, label="PRICE")

    description = forms.CharField(error_messages={
        'required': "Please Enter the Description"
    },  label="DESCRIPTION")

    stock = forms.IntegerField(
      error_messages={
        'required': "Please Enter the Stock"
    },  label="STOCK"
    )

    # def clean(self):
    #     # 기존 기본 유효성 검사를 먼저 호출
    #     cleaned_data = super().clean()
    #     print(cleaned_data)
    #     name=cleaned_data['name']
    #     price=cleaned_data['price']
    #     description=cleaned_data['description']
    #     stock=cleaned_data['stock']

    #     if not(name and price and description and stock):
    #         self.add_error('name', "No Values")
    #         self.add_error('price', "No Values")
    #         self.add_error('description', "No Values")
    #         self.add_error('stock', "No Values")

django/shopping_mall/order/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from .forms import OrderForm
from django.views.generic import ListView
from .models import Order
from user.models import User
from django.utils.decorators import method_decorator
from user.decorator import login_required
from django.db import transaction
from .models import Order
from product.models import Product

# Create your views here.
@method_decorator(login_required, name='dispatch')
class OrderCreate(FormView):
    form_class = OrderForm
    success_url = '/product/'

    def form_valid(self, form):
        with transaction.atomic():
                prod = Product.objects.get(pk=form.data.get('product'))
                order = Order(
                    quantity=form.data.get('quantity'),
                    product =prod,
                    user = User.objects.get(email=self.request.session.get('user'))
                )
                order.save()
                prod.stock -= int(form.data.get('quantity'))
                prod.save()

        return super().form_valid(form)

    def form_invalid(self, form):
        return redirect('/product/'+str(form.data.get('product')))

    def get_form_kwargs(self, **kwargs):
      kw = super().get_form_kwargs(**kwargs)
      kw.update({
        'request' : self.request
      })
      return kw

@method_decorator(login_required, name='dispatch')
class OrderList(ListView):
    # model = Order
    template_name = 'order.html'
    context_object_name = 'order_list'

    def get_queryset(self, **kwargs):
        queryset = Order.objects.filter(user__email=self.request.session.get('user'))
        return queryset

django/shopping_mall/product/views.py
from django.shortcuts import render
from django.views.generic import ListView, FormView, DetailView
from .models import Product
from .forms import RegisterForm
from order.forms import OrderForm
from django.utils.decorators import method_decorator
from user.decorator import login_required, admin_required
from rest_framework import generics, mixins
from .models import Product
from .serializers import ProductSerializer
# Create your views here.


class ProductListAPI(generics.GenericAPIView, mixins.ListModelMixin):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.all().order_by('id')

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


class ProductDetailAPI(generics.GenericAPIView, mixins.RetrieveModelMixin):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.all().order_by('id')
    # RetrieveMixin은 자동으로 url의 pk가져옴.

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
@method_decorator(admin_required, name='dispatch')
class ProductCreate(FormView):
    template_name = 'register_product.html'
    form_class = RegisterForm
    success_url = '/product/'

    def form_valid(self, form):
        product = Product(
            name=form.data.get('name'),
            price=form.data.get('price'),
            description=form.data.get('description'),
            stock=form.data.get('stock'),
        )
        product.save()
        return super().form_valid(form)


class ProductList(ListView):
    model = Product
    template_name = "product.html"
    # context_object_name 설정 안하면, object_list로 넘어감
    context_object_name = 'product_list'


class ProductDetail(DetailView):
    template_name = 'product_detail.html'
    queryset = Product.objects.all()
    context_object_name = 'product'

    # 원하는 정보 같이 넣어서 전달하게 해주는 함수 제공.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderForm(self.request)
        return context

django/shopping_mall/product/templates/product.html
{% extends "base.html"%}
{% load humanize %}
{% block header %}
<script>
  function product_detail(id){
    $(document).ready(function(){
    $.ajax({
        url: '/api/product/'+id,
        success: function(result){
            $("#product-"+id).popover({
              html:true,
              content: result.name + "</br>" + result.price
            }).popover('show');
                }
        });
      })
  }
  function product_leave(id){
    $("#product-"+id).popover("hide");
  }

</script>
{% endblock %}
{% block contents %}

<div class="row mt-5">
  <div class="col-12">
    <table class="table table-light">
      <thead class="thead-light">
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Price</th>
          <th>RTTM</th>
          <th>#</th>
        </tr>
      </thead>
      <tbody class="text-dark">
        {% for product in product_list %}
        <tr>

          <th scope="row">{{ product.id }}</th>
          <th scope="row"><a id="product-{{ product.id }}" onmouseenter="product_detail({{ product.id }})"
            onmouseleave="product_leave({{ product.id }})"
            href="/product/{{product.id}}/">{{ product.name }}</a></th>
          <th scope="row">{{ product.price|intcomma }} Won</th>
          <th scope="row">{{ product.register_date|date:'Y-m-d H:i' }}</th>

        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>


{% for product in product_list %}

{% endfor %}
{% endblock %}

django/shopping_mall/product/templates/product_detail.html
{% extends "base.html"%}
{% load humanize %}
{% block contents %}

<div class="row mt-5">
  <div class="col-12">
          <div class="card" style="width:100;">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <form method="POST" action = "/order/create/">
                  {% csrf_token %}
                  {% for field in form %}

                  <div class="form-group">
                    {% ifnotequal field.label "product" %}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% endifnotequal %}
                    <input type="{{ field.field.widget.input_type }}" class="form-control"
                    id="{{ field.id_for_label }}" placeholder="{{ field.label }}" name="{{ field.name }}"
                    value={% ifequal field.name 'product' %}{{ product.id }}{% endifequal %} />
                  </div>

                  {% if sanghyuk %}
                  <span style="color : red">{{ field.errors }}</span>
                  {% endif %}
                  {% endfor %}
                  <button type="submit" class="btn btn-primary">Order</button>
                </form>
                </li>

                <li class="list-group-item">ID : {{ product.id }}</li>
                <li class="list-group-item">Price : {{ product.price|intcomma }} Won</li>
                <li class="list-group-item">Stock : {{ product.stock|intcomma }}</li>
                <li class="list-group-item">Registered Date : {{ product.register_date|date:'Y-m-d H:i' }}</li>
                <li class="list-group-item">Description : {{ product.description|safe }}</li>
            </ul>
          </div>
  </div>
  <row>
  <div class="col-12">
    <a href="/product/">
    <button type="button" class="btn">Go Back</button>
  </a>
  </div>
</row>
</div>

{% endblock %}

django/shopping_mall/product/templates/register_product.html
{% extends "base.html" %}
{% block header %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script>
  $(document).ready(function() {
      $('#id_description').summernote({
        height:400
      });
  });
</script>
{% endblock %}
{% block contents %}
<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>Register Product</h1>
  </div>
</div>
<div class="row mb-5">
  <div class="col-12 text-danger">
    {{ error }}
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
      <form method="POST" action=".">
        {% csrf_token %}
        {% for field in form %}

        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>

          {% ifequal field.name "description"  %}
          <textarea class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}"></textarea>
          {% else %}
          <input type="{{ field.field.widget.input_type }}" class="form-control"
          id="{{ field.id_for_label }}" placeholder="{{ field.label }}" name="{{ field.name }}">
          {% endifequal %}
        </div>

        {% if field.errors %}
        <span style="color : red">{{ field.errors }}</span>
        {% endif %}
        {% endfor %}


        <button type="submit" class="btn btn-primary">Register</button>
      </form>
  </div>
</div>
{% endblock %}